<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VUNGUYEN-PC" ignored="10" name="GUI_Testing" tests="66" failures="11" timestamp="26 Jul 2021 08:23:28 GMT" time="985.375" errors="0">
  <testcase name="CREATE_incident_by_API" time="3.903" classname="tests.SBP.DHL_APITest"/>
  <testcase name="verify_cancel_incident" time="11.485" classname="tests.SBP.DHL_APITest"/>
  <testcase name="verify_cancel_incident_which_not_in_first_state" time="1.081" classname="tests.SBP.DHL_APITest"/>
  <testcase name="Verify_add_and_delete_Category" time="32.575" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="verify_create_new_incident" time="10.425" classname="tests.SBP.DHL_APITest"/>
  <testcase name="verify_create_new_incident_allow_overwrite" time="11.926" classname="tests.SBP.DHL_APITest"/>
  <testcase name="Verify_add_validation_rule" time="29.727" classname="tests.SBP.DHL_Setting_1">
    <skipped/>
  </testcase> <!-- Verify_add_validation_rule -->
  <testcase name="verify_create_new_incident_not_allow_overwrite" time="11.978" classname="tests.SBP.DHL_APITest"/>
  <testcase name="verify_incorrect_IncidentNbo" time="1.2" classname="tests.SBP.DHL_APITest"/>
  <testcase name="Verify_add_new_custom_fields_numberType" time="23.924" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_add_validation_rule" time="37.941" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_add_new_state_final_state" time="16.899" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_add_new_state_not_final_State" time="18.116" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_create_Subcategory" time="28.672" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_add_new_workflow" time="17.85" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_delete_custom_field" time="33.708" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_delete_validation_rule" time="55.082" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_delete_state" time="34.866" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_edit_validation_rule" time="47.464" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_rename_a_category" time="20.057" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_delete_workflow" time="42.395" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="Verify_update_system_page" time="16.537" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_edit_custom_fields" time="31.087" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="verify_add_new_Incident_Type" time="18.644" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_edit_state" time="24.323" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="verify_delete_incident_type" time="38.128" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="verify_edit_IncidentType" time="32.071" classname="tests.SBP.DHL_Setting_1"/>
  <testcase name="Verify_edit_workflow" time="53.351" classname="tests.SBP.DHL_Setting_2"/>
  <testcase name="verify_assignee_and_coworkerIsMe" time="12.439" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_assignee_and_coworkerIsMe -->
  <testcase name="verify_assignee_and_coworkerIsMe" time="11.971" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_assignee_and_coworkerIsMe -->
  <testcase name="verify_assignee_and_coworkerIsMe" time="12.263" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_assignee_and_coworkerIsMe(DHL_Inbox.java:502)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_assignee_and_coworkerIsMe -->
  <testcase name="verify_assigneeIsMe_and_coworker" time="11.864" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_assigneeIsMe_and_coworker -->
  <testcase name="verify_assigneeIsMe_and_coworker" time="11.984" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_assigneeIsMe_and_coworker -->
  <testcase name="Verify_upload_invalidForm" time="65.083" classname="tests.SBP.DHL_Setting_2">
    <skipped/>
  </testcase> <!-- Verify_upload_invalidForm -->
  <testcase name="verify_assigneeIsMe_and_coworker" time="12.047" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_assigneeIsMe_and_coworker(DHL_Inbox.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_assigneeIsMe_and_coworker -->
  <testcase name="verify_mark_delete_for_an_incident" time="9.199" classname="tests.SBP.DHL_Inbox"/>
  <testcase name="verify_search_incident_by_code" time="12.31" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_search_incident_by_code -->
  <testcase name="verify_search_incident_by_code" time="11.645" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_search_incident_by_code -->
  <testcase name="verify_search_incident_by_code" time="12.482" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_search_incident_by_code(DHL_Inbox.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_search_incident_by_code -->
  <testcase name="Verify_upload_invalidForm" time="64.484" classname="tests.SBP.DHL_Setting_2">
    <skipped/>
  </testcase> <!-- Verify_upload_invalidForm -->
  <testcase name="verify_search_incident_by_last_event_location_and_last_station" time="27.04" classname="tests.SBP.DHL_Inbox"/>
  <testcase name="Verify_upload_invalidForm" time="63.945" classname="tests.SBP.DHL_Setting_2">
    <failure type="java.lang.AssertionError" message="
Notication Element is not dispalyed.
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 
Notication Element is not dispalyed.
 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at tests.SBP.DHL_Setting_2.Verify_upload_invalidForm(DHL_Setting_2.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Verify_upload_invalidForm -->
  <testcase name="verify_search_incident_by_custom_fields" time="46.715" classname="tests.SBP.DHL_Inbox"/>
  <testcase name="verify_update_incident_type_of_incident" time="12.165" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_update_incident_type_of_incident -->
  <testcase name="verify_update_incident_type_of_incident" time="11.953" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_update_incident_type_of_incident -->
  <testcase name="verify_update_incident_type_of_incident" time="11.908" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_update_incident_type_of_incident(DHL_Inbox.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_update_incident_type_of_incident -->
  <testcase name="verify_create_form" time="58.072" classname="tests.SBP.DHL_Event">
    <skipped/>
  </testcase> <!-- verify_create_form -->
  <testcase name="verify_counter_when_creating_new_incidents" time="21.551" classname="tests.SBP.DHL_Inbox"/>
  <testcase name="verify_counter_when_updating_incidents" time="36.838" classname="tests.SBP.DHL_Inbox"/>
  <testcase name="verify_create_form" time="57.897" classname="tests.SBP.DHL_Event">
    <skipped/>
  </testcase> <!-- verify_create_form -->
  <testcase name="verify_incident_state_history" time="12.125" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_incident_state_history -->
  <testcase name="verify_incident_state_history" time="12.623" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_incident_state_history -->
  <testcase name="verify_incident_state_history" time="12.101" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_incident_state_history(DHL_Inbox.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_incident_state_history -->
  <testcase name="verify_incident_state_history_reset_after_changing_incident_type" time="12.0" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_incident_state_history_reset_after_changing_incident_type -->
  <testcase name="verify_incident_state_history_reset_after_changing_incident_type" time="11.864" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_incident_state_history_reset_after_changing_incident_type -->
  <testcase name="verify_create_form" time="59.097" classname="tests.SBP.DHL_Event">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at libraries.verificationFunctions.F_DHLVerification.verifyTemplateForm(F_DHLVerification.java:701)
	at tests.SBP.DHL_Event.verify_create_form(DHL_Event.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_create_form -->
  <testcase name="verify_incident_state_history_reset_after_changing_incident_type" time="52.784" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
	at libraries.SeleniumBrowser.sendKeys(SeleniumBrowser.java:433)
	at libraries.SeleniumBrowser.enter(SeleniumBrowser.java:487)
	at libraries.productFunctions.F_DHLInbox.searchByCode(F_DHLInbox.java:559)
	at tests.SBP.DHL_Inbox.verify_incident_state_history_reset_after_changing_incident_type(DHL_Inbox.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_incident_state_history_reset_after_changing_incident_type -->
  <testcase name="verify_add_new_incident_AutoGenerateCode" time="57.804" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_add_new_incident_AutoGenerateCode -->
  <testcase name="verify_fields_disable_untill_fill_assignee" time="12.015" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_fields_disable_untill_fill_assignee -->
  <testcase name="verify_add_new_incident_AutoGenerateCode" time="24.261" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_add_new_incident_AutoGenerateCode -->
  <testcase name="verify_fields_disable_untill_fill_assignee" time="22.431" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_fields_disable_untill_fill_assignee -->
  <testcase name="verify_add_new_incident_AutoGenerateCode" time="2.397" classname="tests.SBP.DHL_Inbox">
    <failure type="org.openqa.selenium.WebDriverException" message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:39042
Build info: version: &amp;apos;3.141.5&amp;apos;, revision: &amp;apos;d54ebd709a&amp;apos;, time: &amp;apos;2018-11-06T11:42:16&amp;apos;
System info: host: &amp;apos;VUNGUYEN-PC&amp;apos;, ip: &amp;apos;192.168.56.1&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_251&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:39042
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'VUNGUYEN-PC', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at libraries.SeleniumBrowser.clear(SeleniumBrowser.java:460)
	at libraries.productFunctions.F_Navigation.loginDHL(F_Navigation.java:93)
	at tests.SBP.DHL_Inbox.verify_add_new_incident_AutoGenerateCode(DHL_Inbox.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:39042
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 21 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 41 more
]]>
    </failure>
  </testcase> <!-- verify_add_new_incident_AutoGenerateCode -->
  <testcase name="verify_fields_disable_untill_fill_assignee" time="2.672" classname="tests.SBP.DHL_Inbox">
    <failure type="org.openqa.selenium.WebDriverException" message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:45947
Build info: version: &amp;apos;3.141.5&amp;apos;, revision: &amp;apos;d54ebd709a&amp;apos;, time: &amp;apos;2018-11-06T11:42:16&amp;apos;
System info: host: &amp;apos;VUNGUYEN-PC&amp;apos;, ip: &amp;apos;192.168.56.1&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_251&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:45947
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'VUNGUYEN-PC', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at libraries.SeleniumBrowser.clear(SeleniumBrowser.java:460)
	at libraries.productFunctions.F_Navigation.loginDHL(F_Navigation.java:93)
	at tests.SBP.DHL_Inbox.verify_fields_disable_untill_fill_assignee(DHL_Inbox.java:386)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:45947
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 21 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 41 more
]]>
    </failure>
  </testcase> <!-- verify_fields_disable_untill_fill_assignee -->
  <testcase name="verify_add_new_incident_ManualGenerateCode" time="36.27" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_add_new_incident_ManualGenerateCode -->
  <testcase name="verify_add_new_incident_ManualGenerateCode" time="36.778" classname="tests.SBP.DHL_Inbox">
    <skipped/>
  </testcase> <!-- verify_add_new_incident_ManualGenerateCode -->
  <testcase name="verify_add_new_incident_ManualGenerateCode" time="36.323" classname="tests.SBP.DHL_Inbox">
    <failure type="java.lang.AssertionError" message="
Can not find row.
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 
Can not find row.
 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at tests.SBP.DHL_Inbox.verify_add_new_incident_ManualGenerateCode(DHL_Inbox.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verify_add_new_incident_ManualGenerateCode -->
  <testcase name="verify_search_incident_by_status" time="0.0" classname="tests.SBP.DHL_Inbox">
    <ignored/>
  </testcase> <!-- verify_search_incident_by_status -->
  <testcase name="@BeforeSuite beforeTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeTest -->
  <testcase name="@BeforeSuite beforeTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeTest -->
  <testcase name="@BeforeSuite beforeTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeTest -->
  <testcase name="@BeforeSuite beforeTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeTest -->
  <testcase name="@AfterSuite afterTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @AfterSuite afterTest -->
  <testcase name="@AfterSuite afterTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @AfterSuite afterTest -->
  <testcase name="@AfterSuite afterTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @AfterSuite afterTest -->
  <testcase name="@AfterSuite afterTest" time="0.0" classname="tests.DefaultAnnotations">
    <ignored/>
  </testcase> <!-- @AfterSuite afterTest -->
  <testcase name="verify_update_incident_state_without_comment" time="0.0" classname="tests.SBP.DHL_Inbox">
    <ignored/>
  </testcase> <!-- verify_update_incident_state_without_comment -->
</testsuite> <!-- GUI_Testing -->
